name: 新功能提议
title: "[功能提议] " # 默认标题前缀
labels: feature request
assignees: "" # 如果不指定负责人，可以留空

---

**功能名字**
<!-- 请尽量填写 APP还是网页还是小程序 -->
APP

**需要添加的功能内容**
<!-- 请在这里详细描述新功能的实现方法 -->
我希望添加一个新功能，能够在APP主界面直接显示用户最近的活动记录，方便用户快速回顾和管理。